- name: mdns
  tags: [mdns]
  block:
  - name: install avahi-daemon via apt
    when: ansible_pkg_mgr == "apt"
    apt:
      name: avahi-daemon
      state: present
      update_cache: yes

  - name: enable hostname lookup using mdns
    lineinfile:
      dest: /etc/nsswitch.conf
      regexp: '^#?hosts:'
      line: 'hosts:       files mdns_minimal [NOTFOUND=return] dns mdns'
      state: present

  - name: autostart avahi-daemon
    service:
      name: avahi-daemon
      runlevel: "{{ 'default' if ansible_distribution == 'Gentoo' else omit }}"
      enabled: true
