#!/bin/sh

set -e
set -u

einfo() {
    echo "[INFO] >>> $*"
}

eerror() {
    echo "[ERROR] >>> $*" >&2
}

trap 'eerror "Error in $0 on line ${LINENO}."' ERR

einfo 'Updating conf-mgmt ...'
git pull

einfo 'Updating conf-mgmt-private'
cd ../conf-mgmt-private
git pull
