#!/bin/sh

cd "${HOME}"

eval $(dbus-launch --sh-syntax --exit-with-x11)

xset s off
xset -dpms

# Although most of things reads .Xdefaults, qt5 does not, so we need
# to poke it with xrdb as if it was .Xresources.
if [ -f .Xdefaults ]; then
    xrdb -merge .Xdefaults
fi

if [ -f .compton.conf ]; then
    compton  -b &
fi

if [ -f .fehbg ]; then
    sh ~/.fehbg
fi

setxkbmap -layout pl
xset r rate 350 30

if [ -f .xmodmap ]; then
    xmodmap .xmodmap
fi

if [ -f .config/dunstrc ]; then
    dunst &
fi

if command -v autorandr >/dev/null 2>&1; then
    autorandr --change
fi

if [ -f .config/polybar/config.ini ]; then
    # Run polybar after openbox is started
    # so the xwindow module will work as it should.
    # TODO: move most of .xinitrc to openbox startup script...
    ( sleep 1 && polybar >/dev/null 2>&1  ) &
fi

openbox
