#!/bin/sh

get_lock() {
    lock_path="${acpid_state}/action_powersave.lock"

    while :; do 
        if ( set -o noclobber; echo "$$" > "${lock_path}") 2> /dev/null; then 
            break
        else 
            sleep 1
        fi;
    done

    trap 'rm -f "${lock_path}"' INT TERM EXIT
}

sata_link_power_mgmt() {
    if ! compgen -G /sys/class/scsi_host/* >/dev/null 2>&1; then
        return
    fi

    case "$1" in
        'powersave')
            for i in /sys/class/scsi_host/host*/link_power_management_policy; do
                echo min_power >"$i"
            done
        ;;
        'performance')
            for i in /sys/class/scsi_host/host*/link_power_management_policy; do
                echo max_performance >"$i"
            done
        ;;
    esac
}

pci_devices() {
    for i in /sys/bus/pci/devices/*; do
        if ! [ -f "${i}/power/control" ]; then
            continue
        fi

        # Skip network devices, seems to break at least realtek devices.
        if [ -d "${i}/net" ]; then
            continue
        fi

        case "$1" in
            'powersave')
                echo auto >"${i}/power/control"
            ;;
            'performance')
                echo on >"${i}/power/control"
            ;;
        esac
    done
}

snd_hda_intel() {
    case "$1" in
        'powersave')
            echo 1 >/sys/module/snd_hda_intel/parameters/power_save
        ;;
        'performance')
            echo 0 >/sys/module/snd_hda_intel/parameters/power_save
        ;;
    esac
}

sysfs_toggle() {
    # sysfs_toggle <path> <restore|value>

    if ! [ -f "${1}" ]; then
        return
    fi

    state_file="${acpid_state}/saved_state_${1//\//_}"

    case "${2}" in
        'restore')
            if [ -f "${state_file}" ]; then
                cat "${state_file}" >"${1}"
            fi
        ;;
        *)
            cat "${1}" >"${state_file}"
            echo "${2}" >"${1}"
        ;;
    esac
}

ryzen_control() {
    # The power-saving mode forces CPU to boost no more than 2.5 GHz for the first 10s of load.
    # max-performance always boost fully.

    command -v ryzenadj >/dev/null 2>&1 || return 0

    case "$1" in
        'powersave')
            ryzenadj --power-saving
        ;;
        'performance')
            ryzenadj --max-performance
        ;;
    esac
}

acpi_platform_profile() {
    profile="$1"
    if grep -qE '\<'"${profile}"'\>' /sys/firmware/acpi/platform_profile_choices; then
        echo "${profile}" >/sys/firmware/acpi/platform_profile
    fi
}
