#!/bin/sh

scriptpath="$(readlink -f "$0")"
workdir="${scriptpath%/*}"

if ! [ -f /sys/power/disk ]; then
    # No hibernation support.
    exit 0
fi

case "$2" in
    'SBTN'|'PBTN')
        logger -t acpid 'Syncing filesystems ...'
        sync

        logger -t acpid 'Dropping filesystem caches ...'
        echo 1 >/proc/sys/vm/drop_caches

        logger -t acpid 'Running hibernate ...'
        echo disk >/sys/power/state

        logger -t acpid 'Resumed from hibernation.'

        logger -t acpid 'Flushing DNS cache from nscd, if running ...'
        if command -v unscd >/dev/null 2>&1; then
            unscd -i hosts >/dev/null 2>&1
        elif command -v nscd >/dev/null 2>&1; then
            nscd -i hosts >/dev/null 2>&1
        fi

        # While sleeping AC adapter status could change.
        if [ -f "${workdir}/powersave" ]; then
            sleep 3
            "${workdir}/powersave"
        fi
    ;;
esac
