#!/bin/bash

acpid_state='/run/acpid'

sata_link_power_mgmt() {
    if ! compgen -G /sys/class/scsi_host/* >/dev/null 2>&1; then
        return
    fi

    case "$1" in
        'powersave')
            for i in /sys/class/scsi_host/host*/link_power_management_policy; do
                echo min_power >"$i"
            done
        ;;
        'performance')
            for i in /sys/class/scsi_host/host*/link_power_management_policy; do
                echo max_performance >"$i"
            done
        ;;
    esac
}

pci_devices() {
    case "$1" in
        'powersave')
            for i in /sys/bus/pci/devices/*/power/control; do
                echo auto >"$i"
            done
        ;;
        'performance')
            for i in /sys/bus/pci/devices/*/power/control; do
                echo on >"$i"
            done
        ;;
    esac
}

snd_hda_intel() {
    case "$1" in
        'powersave')
            echo 1 >/sys/module/snd_hda_intel/parameters/power_save
        ;;
        'performance')
            echo 0 >/sys/module/snd_hda_intel/parameters/power_save
        ;;
    esac
}

cpu_boost() {
    local state_file boost_toggle

    boost_toggle='/sys/devices/system/cpu/cpufreq/boost'

    if ! [ -f "${boost_toggle}" ]; then
        return
    fi

    state_file="${acpid_state}/original_cpu_boost_state"

    case "$1" in
        'restore')
            if [ -f "${state_file}" ]; then
                cat "${state_file}" >"${boost_toggle}"
            else
                echo 1 >"${boost_toggle}"
            fi
        ;;
        'off')
            cat "${boost_toggle}" >"${state_file}"
            echo 0 >"${boost_toggle}"
        ;;
    esac
}

get_lock() {
    lock_path="${acpid_state}/action_powersave.lock"

    while :; do 
        if ( set -o noclobber; echo "$$" > "${lock_path}") 2> /dev/null; then 
            break
        else 
            sleep 1
        fi;
    done

    trap 'rm -f "${lock_path}"' INT TERM EXIT
}

get_lock

if [ "$4" ]; then
    case "$4" in
        '00000001')
            state='ac'
        ;;
        '00000000')
            state='battery'
        ;;
        *)
            exit 1
        ;;
    esac
else
    if ! [ -d /sys/class/power_supply/AC ]; then
        echo "Looks like there's no power_supply status to probe"
        exit 0
    fi

    read ac_online < /sys/class/power_supply/AC/online
    case "${ac_online}" in
        '1')
            state='ac'
        ;;
        '0')
            state='battery'
        ;;
        *)
            exit 1
        ;;
    esac
fi

# The events can be fired multiple times for one action.
# If we already applied powersave state (and preserved original state of for example boost)
# it's better to not re-apply 'battery' on the top of 'battery' and 'ac' on the top of 'ac'.
if [ "${state}" = "$(cat "${acpid_state}/current_powersave_state" 2>/dev/null)" ]; then
    exit 0
fi

case "${state}" in
    'ac')
        sata_link_power_mgmt performance
        pci_devices performance
        snd_hda_intel performance
        cpu_boost restore
    ;;
    'battery')
        sata_link_power_mgmt powersave
        pci_devices powersave
        snd_hda_intel powersave
        cpu_boost off
    ;;
esac

echo "${state}" >"${acpid_state}/current_powersave_state"
